/**
 * Therapeutic sub-sites inside each destination.
 * Coordinates are real lat/lng for the actual locations — when a user
 * zooms into a destination on the map they see the specific healing
 * spots, not just the town center.
 *
 * Each entry has Arabic source copy plus an English overlay
 * (`nameEn` / `subtitleEn` / `pitchEn`). Use `localizeSite` to get a
 * locale-aware view.
 */

export type TreatmentTag = "مفاصل" | "جلد" | "تنفس" | "توتر" | "استرخاء";

export interface TherapeuticSite {
  id: string;
  destinationId: string;
  name: string;
  subtitle: string;
  /** Optional English overlays — fall back to Arabic when missing. */
  nameEn?: string;
  subtitleEn?: string;
  pitchEn?: string;
  icon: string;
  lat: number;
  lng: number;
  treatments: TreatmentTag[];
  /** Short one-liner shown in the map popup */
  pitch: string;
}

export const THERAPEUTIC_SITES: TherapeuticSite[] = [
  // ── سفاجا (Safaga) ──
  {
    id: "mena-ville",
    destinationId: "safaga",
    name: "مينا فيل",
    nameEn: "Menaville",
    subtitle: "المنتجع العلاجي الأساسي",
    subtitleEn: "The main therapeutic resort",
    icon: "🏖️",
    lat: 26.7453,
    lng: 33.9347,
    treatments: ["جلد", "مفاصل"],
    pitch: "مياه البحر الأحمر + رمال سوداء — العلاج الكلاسيكي",
    pitchEn: "Red Sea water + black sand — the classic therapy",
  },
  {
    id: "abu-soma",
    destinationId: "safaga",
    name: "خليج أبو سوما",
    nameEn: "Abu Soma Bay",
    subtitle: "شعاب مرجانية وشمس علاجية",
    subtitleEn: "Coral reefs and therapeutic sun",
    icon: "🐠",
    lat: 26.8546,
    lng: 33.9846,
    treatments: ["جلد", "تنفس"],
    pitch: "هواء جاف + أشعة UVA/UVB مثالية للصدفية",
    pitchEn: "Dry air + ideal UVA/UVB rays for psoriasis",
  },
  {
    id: "lotus-bay",
    destinationId: "safaga",
    name: "لوتس باي",
    nameEn: "Lotus Bay",
    subtitle: "خليج هادئ للعلاج بالدفن",
    subtitleEn: "A calm bay for sand-burial therapy",
    icon: "🏝️",
    lat: 26.6612,
    lng: 33.95,
    treatments: ["مفاصل", "استرخاء"],
    pitch: "الدفن بالرمال السوداء 15-30 دقيقة للروماتيزم",
    pitchEn: "Black-sand burial for 15–30 minutes for rheumatism",
  },

  // ── سيوة (Siwa) ──
  {
    id: "ain-brezi",
    destinationId: "siwa",
    name: "عين بريزي",
    nameEn: "Ain Brezi",
    subtitle: "كبريتية دافئة + طمي معدني",
    subtitleEn: "Warm sulphur spring + mineral mud",
    icon: "♨️",
    lat: 29.203,
    lng: 25.52,
    treatments: ["جلد", "مفاصل"],
    pitch: "طمي غني بالحديد — معالج قوي للبشرة",
    pitchEn: "Iron-rich mud — a powerful treatment for the skin",
  },
  {
    id: "bir-wahid",
    destinationId: "siwa",
    name: "بئر واحد",
    nameEn: "Bir Wahed",
    subtitle: "ساخنة 70°م + باردة",
    subtitleEn: "Hot 70°C spring + a cold one",
    icon: "🔥",
    lat: 29.1333,
    lng: 25.4667,
    treatments: ["مفاصل", "استرخاء"],
    pitch: "صدمة حرارية تنشّط الدورة الدموية",
    pitchEn: "Thermal-shock therapy to boost blood circulation",
  },
  {
    id: "cleopatra-spring",
    destinationId: "siwa",
    name: "عين كليوباترا",
    nameEn: "Cleopatra Spring",
    subtitle: "قرب معبد آمون",
    subtitleEn: "Near the Temple of Amun",
    icon: "💧",
    lat: 29.2034,
    lng: 25.5455,
    treatments: ["استرخاء", "جلد"],
    pitch: "معدنية + كبريتية — تاريخ يمتد لآلاف السنين",
    pitchEn: "Mineral + sulphuric — with thousands of years of history",
  },
  {
    id: "salt-lakes",
    destinationId: "siwa",
    name: "بحيرات الملح",
    nameEn: "Salt Lakes",
    subtitle: "ملوحة 99% — طفو طبيعي",
    subtitleEn: "99% salinity — natural floating",
    icon: "🧂",
    lat: 29.24,
    lng: 25.58,
    treatments: ["جلد", "استرخاء"],
    pitch: "84 عنصر معدني — تعالج الصدفية والإكزيما",
    pitchEn: "84 minerals — treats psoriasis and eczema",
  },
  {
    id: "salt-cave",
    destinationId: "siwa",
    name: "كهف الملح",
    nameEn: "Salt Cave",
    subtitle: "علاج تنفسي 45 دقيقة",
    subtitleEn: "45-minute respiratory therapy",
    icon: "🕳️",
    lat: 29.205,
    lng: 25.55,
    treatments: ["تنفس", "استرخاء"],
    pitch: "Halotherapy للربو والجيوب الأنفية",
    pitchEn: "Halotherapy for asthma and sinusitis",
  },
  {
    id: "jabal-dakrour",
    destinationId: "siwa",
    name: "جبل الدكرور",
    nameEn: "Jebel Dakrour",
    subtitle: "دفن بالرمال الساخنة",
    subtitleEn: "Hot-sand burial therapy",
    icon: "⛰️",
    lat: 29.18,
    lng: 25.54,
    treatments: ["مفاصل"],
    pitch: "دفن 10-15 دقيقة للروماتويد وآلام الظهر",
    pitchEn: "10–15 minute burial for rheumatoid pain and back pain",
  },

  // ── سيناء (Sinai) ──
  {
    id: "wadi-asal",
    destinationId: "sinai",
    name: "وادي عسل (رأس سدر)",
    nameEn: "Wadi Asal (Ras Sudr)",
    subtitle: "بحيرة كبريتية 200°م عند المنبع",
    subtitleEn: "Sulphur lake at 200°C at the source",
    icon: "🌋",
    lat: 29.5962,
    lng: 32.6667,
    treatments: ["مفاصل", "جلد"],
    pitch: "150 م² — أقوى بحيرة كبريتية في سيناء",
    pitchEn: "150 m² — Sinai's strongest sulphur lake",
  },
  {
    id: "serabit-el-khadim",
    destinationId: "sinai",
    name: "سرابيط الخادم",
    nameEn: "Serabit El-Khadim",
    subtitle: "هضبة 1200م — فيروز وكوارتز",
    subtitleEn: "1200 m plateau — turquoise and quartz",
    icon: "💎",
    lat: 29.0583,
    lng: 33.4667,
    treatments: ["تنفس", "توتر"],
    pitch: "معبد حتحور + أقدم أبجدية في التاريخ",
    pitchEn: "Temple of Hathor + the earliest known alphabet",
  },
  {
    id: "hammam-musa",
    destinationId: "sinai",
    name: "حمام موسى (الطور)",
    nameEn: "Hammam Musa (El-Tor)",
    subtitle: "5 عيون كبريتية 37°م",
    subtitleEn: "5 sulphur springs at 37°C",
    icon: "♨️",
    lat: 28.2333,
    lng: 33.6167,
    treatments: ["جلد", "مفاصل"],
    pitch: "للصدفية والإكزيما والروماتيزم",
    pitchEn: "For psoriasis, eczema, and rheumatism",
  },
  {
    id: "oyoun-musa",
    destinationId: "sinai",
    name: "عيون موسى",
    nameEn: "Oyoun Musa",
    subtitle: "12 عين ذُكرت في التوراة",
    subtitleEn: "12 springs mentioned in the Torah",
    icon: "🌿",
    lat: 29.8333,
    lng: 32.7,
    treatments: ["استرخاء", "تنفس"],
    pitch: "70 نخلة + مياه معدنية — افتُتحت 2018",
    pitchEn: "70 palm trees + mineral water — opened in 2018",
  },

  // ── الفيوم (Fayoum) ──
  {
    id: "whale-valley",
    destinationId: "fayoum",
    name: "وادي الحيتان",
    nameEn: "Wadi Al-Hitan (Whale Valley)",
    subtitle: "تراث يونسكو 2005 — 400+ حفرية",
    subtitleEn: "UNESCO Heritage 2005 — 400+ fossils",
    icon: "🐋",
    lat: 29.2667,
    lng: 30.0333,
    treatments: ["تنفس", "مفاصل", "توتر"],
    pitch: "هواء صحراوي جاف — مثالي لمرضى الحساسية",
    pitchEn: "Dry desert air — ideal for allergy sufferers",
  },
  {
    id: "rayan-springs",
    destinationId: "fayoum",
    name: "عيون الريان",
    nameEn: "Rayan Springs",
    subtitle: "4 ينابيع كبريتية دافئة",
    subtitleEn: "4 warm sulphur springs",
    icon: "💧",
    lat: 29.2,
    lng: 30.4,
    treatments: ["مفاصل", "جلد"],
    pitch: "كبريتيد هيدروجين + مغنسيوم — للروماتيزم",
    pitchEn: "Hydrogen sulphide + magnesium — for rheumatism",
  },
  {
    id: "magic-lake",
    destinationId: "fayoum",
    name: "البحيرة المسحورة",
    nameEn: "The Magic Lake",
    subtitle: "عمق 35م — تتغير ألوانها كل ساعة",
    subtitleEn: "35 m deep — its colours shift every hour",
    icon: "🏞️",
    lat: 29.55,
    lng: 30.1833,
    treatments: ["توتر", "استرخاء"],
    pitch: "استشفاء نفسي + هدوء تام",
    pitchEn: "Mental healing + complete stillness",
  },
  {
    id: "tunis-village",
    destinationId: "fayoum",
    name: "قرية تونس",
    nameEn: "Tunis Village",
    subtitle: "قرية فنية — ورش فخار",
    subtitleEn: "An artists' village — pottery workshops",
    icon: "🏺",
    lat: 29.4633,
    lng: 30.6733,
    treatments: ["توتر", "استرخاء"],
    pitch: "تدليك طبيعي + حجامة + فن يدوي",
    pitchEn: "Natural massage + cupping + handcrafts",
  },

  // ── الواحات البحرية (Bahariya) ──
  {
    id: "white-desert",
    destinationId: "bahariya",
    name: "الصحراء البيضاء",
    nameEn: "The White Desert",
    subtitle: "تكوينات جيرية فريدة",
    subtitleEn: "Unique limestone formations",
    icon: "❄️",
    lat: 27.55,
    lng: 28.5833,
    treatments: ["توتر", "استرخاء"],
    pitch: "استشفاء نفسي — Sense of Awe العلمي",
    pitchEn: "Mental healing — the scientific Sense of Awe",
  },
  {
    id: "black-desert",
    destinationId: "bahariya",
    name: "الصحراء السوداء",
    nameEn: "The Black Desert",
    subtitle: "بازلت وكوارتز",
    subtitleEn: "Basalt and quartz",
    icon: "🏔️",
    lat: 28.0,
    lng: 28.8,
    treatments: ["توتر"],
    pitch: "مشهد بركاني يقلل التوتر بشكل ملحوظ",
    pitchEn: "A volcanic landscape that markedly reduces stress",
  },
  {
    id: "crystal-mountain",
    destinationId: "bahariya",
    name: "جبل الكريستال",
    nameEn: "Crystal Mountain",
    subtitle: "بلورات كوارتز طبيعية",
    subtitleEn: "Natural quartz crystals",
    icon: "💎",
    lat: 27.83,
    lng: 28.7,
    treatments: ["توتر", "استرخاء"],
    pitch: "نقطة تأمل وتوازن نفسي",
    pitchEn: "A point for meditation and inner balance",
  },
  {
    id: "bir-sigam",
    destinationId: "bahariya",
    name: "بئر سيجام",
    nameEn: "Bir Sigam",
    subtitle: "كبريتية ساخنة 45°م",
    subtitleEn: "Hot sulphur spring at 45°C",
    icon: "♨️",
    lat: 28.3356,
    lng: 28.865,
    treatments: ["مفاصل", "استرخاء"],
    pitch: "للروماتيزم ومشاكل الجهاز الهضمي",
    pitchEn: "For rheumatism and digestive issues",
  },

  // ── وادي دجلة (Wadi Degla) ──
  {
    id: "wadi-degla-main",
    destinationId: "wadi-degla",
    name: "المحمية — المدخل الرئيسي",
    nameEn: "The Reserve — Main Entrance",
    subtitle: "طريق القطامية-العين السخنة",
    subtitleEn: "Katameya–Ain Sokhna road",
    icon: "🥾",
    lat: 29.9333,
    lng: 31.4,
    treatments: ["تنفس", "توتر", "استرخاء"],
    pitch: "100+ كم مسارات هايكنج + كانيونات جيرية",
    pitchEn: "100+ km of hiking trails + limestone canyons",
  },
  {
    id: "wadi-degla-canyon",
    destinationId: "wadi-degla",
    name: "الكانيون الكبير",
    nameEn: "The Grand Canyon",
    subtitle: "جدران جيرية ارتفاع 50م",
    subtitleEn: "Limestone walls 50 m high",
    icon: "🏞️",
    lat: 29.925,
    lng: 31.45,
    treatments: ["توتر", "استرخاء"],
    pitch: "هدوء صوتي طبيعي + ظل بارد في الصيف",
    pitchEn: "Natural sound stillness + cool shade in summer",
  },
  {
    id: "wadi-degla-viewpoint",
    destinationId: "wadi-degla",
    name: "نقطة مشاهدة القاهرة",
    nameEn: "Cairo Viewpoint",
    subtitle: "إطلالة بانورامية على المدينة",
    subtitleEn: "A panoramic view over the city",
    icon: "🔭",
    lat: 29.94,
    lng: 31.38,
    treatments: ["توتر", "استرخاء"],
    pitch: "أفضل وقت: ساعة قبل الغروب",
    pitchEn: "Best time: an hour before sunset",
  },
  {
    id: "wadi-degla-fossils",
    destinationId: "wadi-degla",
    name: "منطقة الحفريات",
    nameEn: "Fossil Area",
    subtitle: "حفريات بحرية من عصر الإيوسين",
    subtitleEn: "Marine fossils from the Eocene",
    icon: "🦴",
    lat: 29.92,
    lng: 31.42,
    treatments: ["تنفس", "توتر"],
    pitch: "مشي علمي + هواء جاف للحساسية",
    pitchEn: "Scientific walk + dry air for allergies",
  },

  // ── مزارع شجيع (Shagie Farms) ──
  {
    id: "shagie-main",
    destinationId: "shagie-farms",
    name: "المزرعة الرئيسية",
    nameEn: "The Main Farm",
    subtitle: "ك15 طريق الإسماعيلية-فايد",
    subtitleEn: "Km 15 on the Ismailia–Fayed road",
    icon: "🥭",
    lat: 30.5965,
    lng: 32.2715,
    treatments: ["توتر", "استرخاء"],
    pitch: "Eco-therapy + سياحة المانجو التفاعلية",
    pitchEn: "Eco-therapy + interactive mango tourism",
  },
  {
    id: "shagie-orchard",
    destinationId: "shagie-farms",
    name: "بساتين المانجو",
    nameEn: "Mango Orchards",
    subtitle: "15 صنف مانجو — قطف مباشر",
    subtitleEn: "15 mango varieties — pick them yourself",
    icon: "🌳",
    lat: 30.6,
    lng: 32.28,
    treatments: ["توتر", "استرخاء"],
    pitch: "تجربة حسية كاملة — رائحة + لمس + طعم",
    pitchEn: "A full sensory experience — scent + touch + taste",
  },
  {
    id: "shagie-farm-cafe",
    destinationId: "shagie-farms",
    name: "مقهى المزرعة",
    nameEn: "Farm Café",
    subtitle: "عصائر طازجة + إفطار ريفي",
    subtitleEn: "Fresh juices + a country breakfast",
    icon: "🍹",
    lat: 30.595,
    lng: 32.275,
    treatments: ["استرخاء"],
    pitch: "Mindful eating في الهواء الطلق",
    pitchEn: "Mindful eating in the open air",
  },
  {
    id: "shagie-picnic",
    destinationId: "shagie-farms",
    name: "منطقة البيكنيك",
    nameEn: "Picnic Area",
    subtitle: "ظلال شجر + طاولات خشبية",
    subtitleEn: "Tree shade + wooden tables",
    icon: "🧺",
    lat: 30.598,
    lng: 32.273,
    treatments: ["استرخاء", "توتر"],
    pitch: "Forest bathing + عزلة عن صوت المدينة",
    pitchEn: "Forest bathing + a break from the city noise",
  },
];

export function getSitesForDestination(destinationId: string): TherapeuticSite[] {
  return THERAPEUTIC_SITES.filter((s) => s.destinationId === destinationId);
}

export function getAllSites(): TherapeuticSite[] {
  return THERAPEUTIC_SITES;
}

/**
 * Locale-aware view of a TherapeuticSite. For `ar`, returns the source.
 * For `en`, overlays the optional English fields with per-field fallback
 * so partial translations still render gracefully.
 */
export function localizeSite(
  s: TherapeuticSite,
  locale: "ar" | "en",
): TherapeuticSite {
  if (locale !== "en") return s;
  return {
    ...s,
    name: s.nameEn ?? s.name,
    subtitle: s.subtitleEn ?? s.subtitle,
    pitch: s.pitchEn ?? s.pitch,
  };
}
